git:
  depth: 1
matrix:
  fast_finish: true
language: node_js
node_js:
- '9'
dist: trusty
branches:
  only:
  - master
  - development
before_install:
- yarn
install:
- yarn build
after_success:
- git config --global user.email "oskar@binary.com"
- git config --global user.name "OskarAhl"
- yarn deploy-gh-pages
env:
  global:
  - secure: YC49chht18O8igdkpCyRAl37/6HWcvfbMdpCsrZCIeff0RSFnnia1gMSJuFWb714J1L++8SIqM5C82gfNOpEO0TWcaO0jwuFMPRuX8LPHrMwrSqIVTA3OHlRPylvEJdZpxLhlCkNmVvNy/O6u/MEqeikQOGQTc/NUubvQdGTkQhFlJh/xirqUtfKEAYVeB41mzpYAi7xopoqmnK+JMa0fPyxLIsfhx58+eVXlwRRjTlq5/NyKqRkAhp9a0p7Ac07YHV9eXMVM6xnFTmX5kESXlinFO12Knr7OMjNkMqfqr29BOQknmSz8r9+dI/STnJDB36m1PPTTFzfMgkJjGYGkLtR+reXVNK85qjrjbtGnopMYoZsjkEbI1/5bGwjsIbCZ1mzZn1olGl565ypigD6TUs3lUTRYY/pZXYu6lJ3xJP2+6AMX2OYHzHG1xhkbehS8dDukNWdDjk6x34FJP/42Yk5TU3+AF8mKJ1uDH0YmvFeBwp8c+AEbvYg0spBgDb7V0LrLzygzuHH/tC/ItgJdlPtHAmj6WUj8xHaUknBY7YIO9NdKJf+zOgt9efgEvSeEfQMKwBNMmryUAPBHqeAwHGLCT0lbCBFjY9Vj55mYyYZynNJrkii1ykFgFwt0ut9aKDp39wEUhIljqRntixqqGzgEuoagDKrfuhiuVPds5A=
