git:
  depth: 1
matrix:
  fast_finish: true
language: node_js
node_js:
- '10'
dist: trusty
branches:
  only:
  - master
  - development
before_install:
- npm install -g npm@6.7.0
- npm ci
install:
- npm run build
after_success:
- git config --global user.email $GITHUB_EMAIL
- git config --global user.name $GITHUB_USERNAME
- npm run deploy-gh-pages
env:
  global:
  - secure: kmKNcAlzC8yndawJTEik9H1XyfTs4bCMwh+2Eo1toXOUpx3SpKG6tMuuCH+XpsN084Vxi2dMcidkKeA2Ys9p5v+rH89an2aEe+IeTH7SA/bLBeS51et1IdRsMNd2ALCdi6D+wUNu6DG9taUllOdsRKRzSnBVm7RDTAIY6UEFXEtIouQRy0K7AqRern1NdtPDQQLDZQD0Dse5AXh6qLGLYdEwzAvNlhT72gDe2wUcR3rt3sYuAXoMNFh244G/uGzc3+/0tLdeTxsQZb1VPp6QRuf8rhTz82VNy7aQ5EdiqRS3X/zTp1sCfUuWLNeSaI/XW8gjwrgf9VBeO8KXsr9Iq2Yk02m3Gd90ybDhkVABeXja5W//Wtgyrdpjllvuc8Cdi1kFDTyaqinU6gKhaSZmmrZdcsB0FsYUKEeHx+zboQDvdZh39eAa+QJAWn9qRYx+1peyh6BaOM5BBAUMoYIcgOWJx+4o5aQUIccSFDtt6o8dqZp/Ew1oMWBFv78Zq7GMlsrDS4xtwrGVG8bAZWc6T9Z14W4lH7ZsBrLX4GycPyNd7w5xMMt+npBD4OXhn39qQoMjbEu6z6oz+lDhV3dcjGVAwz4l2oFzaqlOUQiizigYIEAshwH8YhEGZZg1mLp3t0YyhsD7FQ+q2HvlHTNNODupSjOKmOhFKnuTBUHFDPY=
