git:
 depth: 1
matrix:
  fast_finish: true
language: node_js
notifications:
  email:
  - arnab@binary.com
branches:
  only:
  - master
  - development
script:
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- grunt default if:live if:beta
env:
  global:
    secure: "b1Ddy0glvPsn6q4ebyZ8G+/SqXZKNR5RyvFzhX8k0EFNVQFR3HYdSxievAbDVpGWg8c7yTiSNdGcIJiA4GH9H4YZOtcKQcBDwWDQLdA3o9F/LuOMPi1kx1CnBTp9kxs0pxzScrY6Aw/hiXKG5vSgGcdL5WWFCERbhPoWTiabvoSwfg7fglsRohbd5bBFex3uPxW63cC8wszAduNe/NNBeB8YHsWc/g7fVl3IpsIQEFbI2Yh6uL5ElqCrNJKxaiMwwibEwPdk2AA3vgYD0kgEJXQhB/Db2iSFgIE0LAqCKmcHBApxkdkdbAqa55E160q90n6fKEH93PXVasXlID8QBgCi7FyMNok/m4uURfpSQDTIvXUk/JpIF//H2+Ys6p9TED31jEPRtsRl0EwPEy9FhArzvdWEOgKmSLE3r0lGHmkCu0t4TnLOoYC2uGqPHsl489VXJEB952YrG6gbFZq0ZDAT7b8bMge95EoJhS0xV8QD5iMYzi53pYFLMS/yJAQtcm1WXjG7v6VkZGonLtBQHfoXzrSRXP9oCbBDxdJk3OV5Ar3yC20JQdWjQpT6xPDzpIMVyS5BEzs3sFZ5GASNwCAixCipOlmgQvwUOM9fn+lf6uhOD9V/Wt+Yfwz/SZUhHsaqHtG9n9ZN9Lxb9vlpR6hxNdAtB2/ax4MvFThnW1Y="
