git:
  depth: 1
matrix:
  fast_finish: true
language: node_js
node_js:
- '10'
dist: trusty
branches:
  only:
  - master
  - development
before_install:
- npm install -g npm@6.7.0
- npm ci
install:
- npm run build
after_success:
- git config --global user.email $GITHUB_EMAIL
- git config --global user.name $GITHUB_USERNAME
- npm run deploy-gh-pages
