git:
  depth: 1
matrix:
  fast_finish: true
language: node_js
node_js:
- '9'
dist: trusty
branches:
  only:
  - master
  - development
before_install:
- yarn
install:
- yarn build
after_success:
- git config --global user.email "oskar@binary.com"
- git config --global user.name "OskarAhl"
- yarn deploy-gh-pages
env:
  global:
  - secure: Yt3BuUbNMZ6oQymLWTPXEHWqLodW1W+FSfKD7bWYkexf5hUbzLxKu6MP8ZGf36Y5vJ8skBcWwzhwsRhTUQyFAVjJMcSg3+qqO7QviAGboHCSIY41e/idgPIhuhmNg//lTSP3h11bWuj6MXQ5EFPBMPuqJZzpZb5VxGPt/mRVMCY1yJdXgL3oS9GOCs/WsNacFZpAS1DXUSjt7lq/Uz2kjdrKQxLcyE1xHGOIXZWVe0HonlhDddv+sxuNPjzjutcHvKLTcQJ7FX3lf/VrvlT0K1sm7jPtMral2a4fos7q4VNebWv3I6EK0PQKud4fn6IWBdGlJjIvhkzRcy8CRMi9/ETYb2BTvBCuedr6DHvkJdGUPWrDsBP83JqYUUxSm6Cg4gIuGrINz8gGprwY1gDMdHt78cjxeSQ8egsN4nORJnliTzvPiRuNE0N4DFu320xo/FtF10afF8RXAOIUW2mq9+pzcunhACgrMC20esdMyevHrdjhN1uL7Jgk5na/+7E3eg4TOEUiWkqEO3vYXgJ09zOZc5IdDcOmVKwmsohC7kfj4oE6/5BsLp72aFDtbrxcpefrGSeKukj9HSp2vvm2wEW5bPISIqnQyhGgdb+7OyEkMZ0khZ1ngza7815F6mCmVM1JmsMTutzAjPVdJ+i6T0muFl4GFNYcXsxOPHMlaUY=
